In [5]:
import numpy as np
from scipy.special import expit
import random

In [45]:
class neural_network:
    
    def __init__(self, X, y, layers):
        self.X = X
        self.y = y
        self.layers = [len(X[0])] + layers + [len(y[0])]
        self.num_layers = len(self.layers)
        self.n = self.num_layers - 1
        self.z = [np.zeros((l_i, 1)) for l_i in self.layers]
        self.a = [np.zeros((l_i, 1)) for l_i in self.layers]
        self.W = [np.random.rand(self.layers[i+1], self.layers[i])
                        for i in range(self.n)]
        
        self.dW = [np.zeros((self.layers[i+1], self.layers[i]))
                        for i in range(self.n)]
    
                           
    def sigmoid(self,x):
        return 1/(1+np.exp(-x))

    def sigmoid_derivative(self,x):
        return self.sigmoid(x)*(1 - self.sigmoid(x))
    
    def derivative_az(self, layer):
        return np.diag([self.sigmoid_derivative(self.z[layer][j, 0]) 
                        for j in range(self.layers[layer])
                           ])
    
    def derivative_za(self, layer):
        return self.W[layer-1]

    def error(self, sample):
        return sum((self.y[sample][j] - self.z[self.n][j,0])**2 for j in range(self.layers[self.n])) 
    
    def negative_error_derivative(self, t):
        return self.learning_rate * np.array([[2*(self.y[t][j] - self.z[self.n][j,0]) for j in range(self.layers[self.n])]]) 
    
    def feedforward(self):
        for layer in range(1, self.num_layers):
            self.z[layer] = self.W[layer-1] @ self.a[layer-1]
            self.a[layer] = self.sigmoid(self.z[layer])
    
    def backprop(self, sample):
        delta = self.negative_error_derivative(sample)
        self.dW[self.n - 1] = self.dW[self.n - 1] + (np.transpose(delta) @
                                                     np.transpose(self.a[self.n]))
        for layer in range(self.n-2, -1, -1):
            delta = delta * za_derivative(layer+2) * az_derivative(layer+1)
            self.dW[layer] = self.dW[layer] + (np.transpose(delta) 
                                               @ np.transpose(self.a[layer]))
            
    
    def train(self, epochs, learning_rate):
        self.learning_rate = learning_rate
        for epoch in range(epochs):
            self.dW = [np.zeros((self.layers[i+1], self.layers[i]))
                        for i in range(self.n)]
            
            epoch_error = 0
            for sample in range(len(self.X)):
                self.a[0] = [self.X[sample]]
                self.feedforward()
                epoch_error += self.error(sample)
                self.backprop(sample)
                   
            print("EPOCH: "+ epoch + "   ERROR: "+epoch_error)

            for layer in range(0, self.n):
                self.W[layer] = self.W[layer] + self.dW[layer]
            
    def test(self, X_test):
        outputs = []
        for x in X_test:
            self.a[0] = x;
            self.feedforward()
            outputs.append(self.z[self.n])
        
        return outputs
        


In [20]:
X = np.array([[random.randint(1, 10)] for i in range(100)])

In [34]:
X

array([[ 1],
       [ 2],
       [ 1],
       [ 9],
       [ 7],
       [ 8],
       [ 5],
       [ 7],
       [ 3],
       [ 3],
       [10],
       [ 7],
       [ 1],
       [ 5],
       [ 2],
       [ 2],
       [ 3],
       [ 3],
       [ 3],
       [ 1],
       [ 8],
       [ 6],
       [ 1],
       [ 4],
       [ 8],
       [ 1],
       [ 7],
       [ 1],
       [ 8],
       [ 5],
       [ 1],
       [10],
       [ 5],
       [ 8],
       [ 6],
       [ 2],
       [ 9],
       [ 5],
       [ 7],
       [ 3],
       [ 7],
       [ 2],
       [ 7],
       [ 7],
       [ 8],
       [ 3],
       [ 6],
       [ 6],
       [ 7],
       [ 9],
       [ 2],
       [ 3],
       [ 8],
       [ 1],
       [ 3],
       [10],
       [ 8],
       [10],
       [ 8],
       [ 8],
       [ 1],
       [ 6],
       [ 1],
       [ 4],
       [ 9],
       [ 3],
       [ 9],
       [ 4],
       [ 7],
       [ 4],
       [ 5],
       [10],
       [ 9],
       [ 4],
       [ 9],
       [ 6],
       [10],

In [35]:
Y = np.array([[2*X[i, 0]] for i in range(100)])

In [36]:
X

array([[ 1],
       [ 2],
       [ 1],
       [ 9],
       [ 7],
       [ 8],
       [ 5],
       [ 7],
       [ 3],
       [ 3],
       [10],
       [ 7],
       [ 1],
       [ 5],
       [ 2],
       [ 2],
       [ 3],
       [ 3],
       [ 3],
       [ 1],
       [ 8],
       [ 6],
       [ 1],
       [ 4],
       [ 8],
       [ 1],
       [ 7],
       [ 1],
       [ 8],
       [ 5],
       [ 1],
       [10],
       [ 5],
       [ 8],
       [ 6],
       [ 2],
       [ 9],
       [ 5],
       [ 7],
       [ 3],
       [ 7],
       [ 2],
       [ 7],
       [ 7],
       [ 8],
       [ 3],
       [ 6],
       [ 6],
       [ 7],
       [ 9],
       [ 2],
       [ 3],
       [ 8],
       [ 1],
       [ 3],
       [10],
       [ 8],
       [10],
       [ 8],
       [ 8],
       [ 1],
       [ 6],
       [ 1],
       [ 4],
       [ 9],
       [ 3],
       [ 9],
       [ 4],
       [ 7],
       [ 4],
       [ 5],
       [10],
       [ 9],
       [ 4],
       [ 9],
       [ 6],
       [10],

In [24]:
Y

array([[ 2],
       [ 4],
       [ 2],
       [18],
       [14],
       [16],
       [10],
       [14],
       [ 6],
       [ 6],
       [20],
       [14],
       [ 2],
       [10],
       [ 4],
       [ 4],
       [ 6],
       [ 6],
       [ 6],
       [ 2],
       [16],
       [12],
       [ 2],
       [ 8],
       [16],
       [ 2],
       [14],
       [ 2],
       [16],
       [10],
       [ 2],
       [20],
       [10],
       [16],
       [12],
       [ 4],
       [18],
       [10],
       [14],
       [ 6],
       [14],
       [ 4],
       [14],
       [14],
       [16],
       [ 6],
       [12],
       [12],
       [14],
       [18],
       [ 4],
       [ 6],
       [16],
       [ 2],
       [ 6],
       [20],
       [16],
       [20],
       [16],
       [16],
       [ 2],
       [12],
       [ 2],
       [ 8],
       [18],
       [ 6],
       [18],
       [ 8],
       [14],
       [ 8],
       [10],
       [20],
       [18],
       [ 8],
       [18],
       [12],
       [20],

In [46]:
nn = neural_network(X, Y, [])

In [38]:
nn.layers

[1, 1]

In [39]:
nn.num_layers

2

In [40]:
nn.n

1

In [41]:
nn.z

[array([[0.]]), array([[0.]])]

In [42]:
nn.a

[array([[0.]]), array([[0.]])]

In [43]:
nn.W

[array([[0.10554882]])]

In [47]:
nn.train(10, 0.1)

UnboundLocalError: local variable 'layer' referenced before assignment